version: "3.8"

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    user: root
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ALLOW_RESET=TRUE
    volumes:
      - index_data:/chroma/chroma
    ports:
      - "8000:8000"
    networks:
      - net

  mongodb:
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    networks:
      - net
    volumes:
      - type: bind 
        source: ./data
        target: /data/db
volumes:
  index_data:
    driver: local

networks:
  net:
    driver: bridge